// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("otlphttp")
	ScopeName = "github.com/t00mas/otlphttpexporter"
)

const (
	ProfilesStability = component.StabilityLevelDevelopment
	LogsStability     = component.StabilityLevelBeta
	TracesStability   = component.StabilityLevelStable
	MetricsStability  = component.StabilityLevelStable
)
